---
# This role contains the wake on lan procedure.

- name: Send magic Wake-On-Lan packet to {{host_mac}} via broadcast {{wol_broadcast}}
  wakeonlan:
    mac: '{{host_mac}}'
    broadcast: '{{wol_broadcast}}'
  delegate_to: localhost

- name: Wait {{connection_timeout}} seconds for system to become reachable
  wait_for_connection:
    timeout: '{{connection_timeout}}'

- name: Gather facts for first time
  setup: